### PR TITLE
Made responsive, fade on stories load

### PR DESCRIPTION
**Pull request by neauoire**

### CODE REVIEW

**Comment by neauoire** [comment]
Fixes the sizing issues: 

Where the coordinates are cut at the bottom:

Screen Shot 2019-06-02 at 9 30 41 AM

And the pin placeholder is cut at the top:

Screen Shot 2019-06-02 at 9 30 46 AM

Making it responsive :)

Screen Shot 2019-06-02 at 9 31 08 AM

It even fades in when the stories are loaded, so it doesn't flicker on boot 👍

**Comment by vi-ctorivanov** [comment]
Thanks Devine! I'll merge when I'm back home, today :)

**Comment by vi-ctorivanov** [comment]
I manually implemented your changes with some slight modifications, thank you so much!

I reorganized a few things since this PR was made so I felt the conflict resolving would be more trouble than manual implementation.

**Comment by neauoire** [comment]
np

**Pull request closed without merging**
